### ISSUE TITLE
Question about extracting SFC-processing

### ISSUE THREAD

**Issue by dennisreimann** [eddyerburgh/vue-jest#24]
I am wondering if it would make sense to extract the vue file processing into a separate module, so that other tools could benefit from the existing solution in vue-jest as well. Right now there a several different modules handling the parsed output from vue-template-compiler (vue-jest, vue-loader, vueify or jest-vue-preprocessor).
Background: I am currently working on a project that needs to consume vue files independent from a concrete implementation (like processing via vue-loader or vueify) and came here, because vue-jest does exactly what I would need. But of course vue-jest does not expose the processing functionality, because it serves another purpose.

Does this make sense?

**Comment by eddyerburgh** [comment]
Yes, it makes perfect sense 😀!

We're already doing this in the vue-component-compiler —https://github.com/vuejs/vue-component-compiler/pull/29 

The PR is nearly ready to be merged. We're waiting for a review from Evan. I think it will be a month or two before it's released.

I won't be doing this from vue-jest itself, so I'm closing the issue.

**Comment by dennisreimann** [comment]
Nice, thanks for the feedback! :cake:
