### ISSUE TITLE
How to write the test when components access instance/global method?

### ISSUE THREAD

**Issue by amigoge** [eddyerburgh/vue-jest#33]
Hi,I use the jest to test my component.But I hit a problem.

When I run the unit test I write, the component invoke the instance method will cause an error.

So how should I change my testing code or the implement of the component?

cmpA.vue

    export default{
      ...
      methods:{
        // the component itself's method
        innerCall:function(){
          // to invoke the instance/global method
          this.Global.test().then(...).catch(...);
        }
      }
    }

cmpA.spec.js

    import { shallow } from "vue-test-utils";
    import captcha from "@/components/captcha";

    describe("cmpA.spec.js",()=>{
      const createCmp = propsData => shallow(captcha, {propsData})
      let component;

      beforeEach(() => {
        component = createCmp();
      });
      it("test the cmpA's innerCall method.", () => {
        const stub = jest.fn();
        component.setMethods({innerCall: stub});
        // just for finish the unit test first
        expect(true).toEqual(true);
      });
    })

**Comment by eddyerburgh** [comment]
Hi, this is a question for StackOverflow. The issue tracker is reserved for bug reports and feature requests.

You should look at the `mocks` method of vue-test-utils, that adds properties to the instance—https://vue-test-utils.vuejs.org/en/api/options.html#mocks

If you have any further questions, please ask on StackOverflow.
